import * as dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  CORS_ORIGIN,
  NODE_ENV,

  MONGODB_URL,
  MONGODB_NAME,

  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,

  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_FOLDER_NAME,

  MAILTRAP_SMTP_HOST,
  MAILTRAP_SMTP_PORT,
  MAILTRAP_SMTP_USERNAME,
  MAILTRAP_SMTP_PASSWORD,
  MAILTRAP_SENDEREMAIL,

  EMAIL_VERIFICATION_TOKEN_EXPIRY,
} = process.env;
